# Generated by Django 4.2 on 2024-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_like_options_rename_created_on_like_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/post_file/'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_image/'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/post_video/'),
        ),
    ]
