# Generated by Django 4.2 on 2024-11-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_bio_alter_profile_image'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friendship',
            new_name='Connection',
        ),
    ]
