# Generated by Django 4.2 on 2024-11-28 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_alter_postfile_file_alter_postfile_image_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='accountreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/account_report_images/'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_report_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='accountreport',
            unique_together={('reporter', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('reporter', 'post')},
        ),
    ]
