# Generated by Django 4.2 on 2024-11-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_accountreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreport',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accountreport',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
